CREATE DATABASE app;

USE app;

--PEOPLE TABLE
CREATE TABLE PEOPLE (
    fullname VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
);

--ANIMALS TABLE
CREATE TABLE ANIMALS (
    rescue_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    type VARCHAR(100) NOT NULL,
    sex VARCHAR(100) NOT NULL,
    status VARCHAR(100) NOT NULL,
    particular_signs TEXT NOT NULL,
);

--PHOTOS TABLE 
CREATE TABLE PHOTOS (
    url TEXT NOT NULL,
    ANIMAL,
)

--ADOPTIONS TABLE
CREATE TABLE ADOPTIONS (
    ANIMAL,
    PEOPLE,
    -- PERMANENT/TEMPORAL
    type V
    adoption_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
);